import { chromium } from "playwright";
const WP=(process.env.BEQUEEN_WP_BASE||"").replace(/\/+$/,""), KEY=process.env.BEQUEEN_COLLECTOR_KEY||"", PROBE="ENO25400471EG";
const PAGE="https://egyptpost.gov.eg/ar-eg/home/eservices/track-and-trace/", sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function once(page,barcode){return page.evaluate(async({barcode})=>{const c=new AbortController(),t=setTimeout(()=>c.abort(),60000);try{const r=await fetch(`/ar-EG/TrackTrace/GetShipmentDetails?barcode=${encodeURIComponent(barcode)}`,{credentials:"include",headers:{Accept:"application/json, text/plain, */*"},signal:c.signal});const text=await r.text();let body=null;try{body=JSON.parse(text)}catch{}return{http:r.status,cf:r.headers.get("cf-mitigated"),ct:r.headers.get("content-type"),body,preview:body?null:text.slice(0,500)}}catch(e){return{http:null,cf:null,ct:null,body:null,error:String(e)}}finally{clearTimeout(t)}},{barcode})}
const usable=r=>r?.http===200&&!r?.cf&&String(r?.ct||"").toLowerCase().includes("application/json");
async function jsonFetch(url,opt={}){const r=await fetch(url,opt),text=await r.text();let j;try{j=JSON.parse(text)}catch{}if(!r.ok)throw Error(`HTTP ${r.status}: ${text.slice(0,500)}`);return j}
async function ready(page){const nav=await page.goto(PAGE,{waitUntil:"domcontentloaded",timeout:60000}).catch(()=>null);console.log("Navigation HTTP:",nav?.status?.()??null,"TITLE:",await page.title().catch(()=>""));const s=Date.now();let i=0;while(Date.now()-s<120000){const r=await once(page,PROBE);console.log(`[probe ${++i}]`,JSON.stringify({http:r.http,cfMitigated:r.cf,contentType:r.ct,success:r.body?.success??null,case:r.body?.data?.case??null,eventCount:Array.isArray(r.body?.data?.data)?r.body.data.data.length:null,preview:r.preview,error:r.error}));if(usable(r)){console.log("Usable JSON session confirmed; provider success may be true or false.");return}await sleep(5000)}throw Error("Egypt Post browser session did not become usable within 120s")}
async function track(page,barcode){for(const delay of [0,5000,15000]){if(delay)await sleep(delay);const r=await once(page,barcode);if(usable(r)&&r.body?.success===true)return{ok:true,raw:r.body,d:r};if(usable(r))console.log(`${barcode}: usable JSON but success=false; retrying`);var last=r}return{ok:false,raw:null,d:last}}
async function main(){if(!WP||!KEY)throw Error("Missing WordPress secrets");const browser=await chromium.launch({headless:true}),ctx=await browser.newContext({locale:"ar-EG",viewport:{width:1365,height:900}}),page=await ctx.newPage();try{await ready(page);const q=await jsonFetch(`${WP}/wp-json/bequeen-app/v1/collector/shipments`,{headers:{"X-BeQueen-Collector-Key":KEY,Accept:"application/json"}}),items=Array.isArray(q)?q:(q.shipments||q.data||[]),results=[];console.log("Active shipments:",items.length);for(const item of items){const b=item.tracking_number||item.barcode;if(!b)continue;const g=await track(page,b);results.push({order_id:item.order_id,tracking_number:b,success:g.ok,raw:g.raw,error:g.ok?null:{http:g.d?.http??null,cf_mitigated:g.d?.cf??null,content_type:g.d?.ct??null,provider_success:g.d?.body?.success??null,message:g.d?.error||"Provider did not return success"},collected_at:new Date().toISOString()});await sleep(2000)}console.log("Ingest:",await jsonFetch(`${WP}/wp-json/bequeen-app/v1/collector/results`,{method:"POST",headers:{"X-BeQueen-Collector-Key":KEY,"Content-Type":"application/json"},body:JSON.stringify({results})}))}catch(e){try{await page.screenshot({path:"egyptpost-debug.png",fullPage:true});(await import("node:fs")).writeFileSync("egyptpost-debug.html",await page.content())}catch{}throw e}finally{await browser.close()}}
main().catch(e=>{console.error(e);process.exit(1)});
